name: Beta Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version/Tag for the release'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 1

      - name: Install packages & setup
        run: |
          sudo apt update -y     
          sudo apt install wget default-jdk git-core gnupg flex bison gperf build-essential zip curl libc6-dev libncurses5-dev x11proto-core-dev libx11-dev libreadline6-dev libgl1-mesa-glx libgl1-mesa-dev python3 make sudo gcc g++ bc grep tofrodos python3-markdown libxml2-utils xsltproc zlib1g-dev libncurses5 python-is-python3 libc6-dev libtinfo5 ncurses-dev make python2 repo cpio kmod openssl libelf-dev pahole libssl-dev libelf-dev -y
          bash init_clang_12.sh

      - name: Run build
        run: |
          export PATH=$HOME/:$PWD/toolchain/proton-clang/bin:$PATH
          bash build_kernel.sh -c

      - name: Generate Changelog
        run: |
          echo "## Changelog" > CHANGELOG.md
          git log --format="- %s (%h)" ${{ github.event.before }}..${{ github.sha }} >> CHANGELOG.md

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: "LPoS Kernel [${{ github.event.inputs.version }}] [S10 5G]"
          body: |
            $(cat CHANGELOG.md)

      - name: Upload kernel
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: out/*.tar
          asset_name: "LPoS Kernel [${{ github.event.inputs.version }}] [S10 5G].tar"
          asset_content_type: application/tar
