name: build and release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true        

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        varient: [ksu, clean]
    name: "🚧 Build for ${{matrix.varient}}"
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install packages & setup
        run: |
          sudo apt update -y        
          sudo apt install libncurses5-dev python2 libtinfo5 -y
          bash init_clang_12.sh
          
      - name: Set environment variable
        run: |
          echo "LPOS_KERNEL_VERSION=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          
      - name: Building LPoS ${{matrix.varient}} 
        run: |
          bash build_kernel.sh -${{matrix.varient}}

      - name: Upload kernel
        uses: actions/upload-artifact@v4
        with:
          name: "LPoS_${{ env.LPOS_KERNEL_VERSION }}_${{matrix.varient}}_[S10 5G]"
          path: |
            out/LPoS*.xz
            out/KSU*.xz

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.tag }}
          name: "LPoS Kernel ${{ env.LPOS_KERNEL_VERSION }}"
          draft: false
          prerelease: false
          token: ${{ secrets.TOKEN }}          
          artifacts: "out/LPoS*.xz,out/KSU*.xz"
          body: "Commit SHA: ${{ github.sha }}"
