name: build

on:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 1

      - name: Install packages & setup
        run: |
          sudo apt update -y ; sudo apt upgrade -y
          sudo apt purge firefox -y          
          sudo apt install wget python3 python2 openssl python-is-python3 -y
          bash init_clang_12.sh
          
      - name: Run build
        run: |
          export PATH=$HOME/:$PWD/toolchain/proton-clang/bin:$PATH
          bash build_kernel.sh -c

      - name: Upload kernel
        uses: actions/upload-artifact@v3.1.2
        with:
          name: "LPoS Kernel [v8.5.1] [S10 5G]"
          path: out/*.tar