name: build

on:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 1

      - name: Install packages & setup
        run: |
          sudo apt update -y ; sudo apt upgrade -y
          sudo apt purge firefox -y          
          sudo apt install wget default-jdk git-core gnupg flex bison gperf build-essential zip curl libc6-dev libncurses5-dev x11proto-core-dev libx11-dev libreadline6-dev libgl1-mesa-glx libgl1-mesa-dev python3 make sudo gcc g++ bc grep tofrodos python3-markdown libxml2-utils xsltproc zlib1g-dev libncurses5 python-is-python3 libc6-dev libtinfo5 ncurses-dev make python2 repo cpio kmod openssl libelf-dev pahole libssl-dev libelf-dev -y
          bash init_clang_12.sh
          
      - name: Run build
        run: |
          export PATH=$PWD/toolchain/proton-clang/bin:$PATH
          bash auto_workflow_clang.sh

      - name: Upload kernel
        uses: actions/upload-artifact@v3.1.2
        with:
          name: N_kernel_Proton-Clang_12
          path: AIK/N_KERNEL.*_PROTON_CLANG_12_LATEST.zip