name: Build Kernel

on:
  push:
  workflow_dispatch:
    inputs:      
      tag:
        description: 'Release Tag'
        required: true    

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        device: [S10-5G, S10, S10+, S10e]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install packages & setup
        run: |
          sudo apt update -y
          sudo apt install libssl-dev libncurses5-dev python2 libtinfo5 -y
          git clone --depth=1 https://github.com/kdrag0n/proton-clang -b master toolchain
          echo "LPOS_KERNEL_VERSION=${{ github.event.inputs.tag }}" >> $GITHUB_ENV

      - name: Building LPOS ${{ matrix.device }}
        run: |
          DEVICE=${{ matrix.device }} ./build.sh

      - name: Building LPoS + KernelSU
        run: |
          DEVICE=${{ matrix.device }} ./build.sh -k  

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "LPOS_${{ matrix.device }}"
          path: |
            out/${{ matrix.device }}/*.zip 

  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: "LPOS_${{ matrix.device }}"

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.tag }}
          name: "LPoS Kernel ${{ github.event.inputs.tag }}"
          draft: false
          prerelease: false
          token: ${{ secrets.TOKEN }}          
          artifacts: out/${{ matrix.device }}/*.zip
          body: "Commit SHA: ${{ github.sha }}"

      - name: Upload to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          document: out/${{ matrix.device }}/*.zip
          format: html
          disable_web_page_preview: false
          message: |
            <b>New Kernel Build found..! 🎉</b>
            
            <b>Devices :</b> Universal S10   
            <b>Kernel Version :</b> ${{ github.event.inputs.tag }}                    
            <b>Repository:</b> <a href="https://github.com/${{ github.repository }}">${{ github.repository }}</a>
            
            <b>Commit SHA:</b> <a href="https://github.com/${{ github.repository }}/commit/${{github.sha}}">Click here</a>
            
            <b>Installation :</b> <a href="https://telegra.ph/LPoS-Kernel-Installation-Guide-02-09">Click here</a>